### ISSUE TITLE
How to compile xd

### ISSUE THREAD

**Issue by ZephyrGT** [Fyrax-exe/bucketware#4]
Hello there is 2 cons
1-Cant compile there is coredata main.cpp error
2-Its eating so much cpu waiting you to fix :)
3-Have a good day and ramadan :D

**Comment by Fyrax-exe** [comment]
1-Make sure you have c++ vs tools
or try search problmen from web
2-Yeaa.. its for now eating cpu but i optimizate it tomorrow and there is low cpu checkbox in Options menu what should help little bit

**Comment by ZephyrGT** [comment]
Okay but why its eating so much cpu and who are you :D?

**Comment by ZephyrGT** [comment]
I can fix that easily but if anyone trys to compile without any knowledge they will stuck xd

**Comment by Fyrax-exe** [comment]
Okay

**Comment by ZephyrGT** [comment]
Who are you i never heard Fyrax-exe :)?

**Comment by Fyrax-exe** [comment]
Fyrax

**Comment by ZephyrGT** [comment]
Well are you in any discord server or smth ?

**Comment by Fyrax-exe** [comment]
No but i have own server for this project
[here](https://discord.gg/Nb4295JK)
