### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SoysalV** [Fyrax-exe/bucketware#5]
![image](https://user-images.githubusercontent.com/74335368/115158778-98905100-a098-11eb-9f79-e3ff1a0c9d85.png)

**Comment by Fyrax-exe** [comment]
Run it as debug mode in vs that you can see what trhows that errror

**Comment by SoysalV** [comment]
> Run it as debug mode in vs that you can see what trhows that errror

Thats when starting enet

**Comment by Fyrax-exe** [comment]
Oh yeah.. proxy system isnt ready yet

**Comment by ZephyrGT** [comment]
Just use growbrew for now :)

**Comment by Fyrax-exe** [comment]
Yea i fix proxy today
