### ISSUE TITLE
failed to laod enet dynamic library error

### ISSUE THREAD

**Issue by Altanb1337** [Fyrax-exe/bucketware#6]
![image](https://user-images.githubusercontent.com/81725126/121075040-599b9380-c7dd-11eb-8386-41ace05713cc.png)

**Comment by Fyrax-exe** [comment]
Do you have  64-bit pc?

**Comment by Altanb1337** [comment]
> Do you have 64-bit pc?

yes

**Comment by Altanb1337** [comment]
btw when i try to build it gives memory error  system memory 4.5.1 installed

**Comment by Fyrax-exe** [comment]
try add memory dll to project you can download it from [here](https://cdn.discordapp.com/attachments/851010233241305109/851666194917621790/Memory.dll)

**Comment by Altanb1337** [comment]
I already fixed memory issue but how to fix enet issue?

**Comment by Altanb1337** [comment]
![image](https://user-images.githubusercontent.com/81725126/121127909-300d5700-c833-11eb-933b-ce0167cab5cc.png)

Failed to load integrity or integrated or one of the patterns 'Memory, Version=1.2.21.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an invalid size

**Comment by Altanb1337** [comment]
![image](https://user-images.githubusercontent.com/81725126/121131042-ea06c200-c837-11eb-84fb-311a6051252e.png)

**Comment by Cydent** [comment]
If growtopia was interrupted, AoB scan would not be successfull so it would auto ban

**Comment by Altanb1337** [comment]
> ![image](https://user-images.githubusercontent.com/81725126/121127909-300d5700-c833-11eb-933b-ce0167cab5cc.png)
> 
> Failed to load integrity or integrated or one of the patterns 'Memory, Version=1.2.21.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an invalid size

How to fix this

**Comment by Fyrax-exe** [comment]
how you can get all possible errors XDD did you build it as x64

**Comment by Altanb1337** [comment]
> how you can get all possible errors XDD did you build it as x64

Yes
