### ISSUE TITLE
world brute forcer

### ISSUE THREAD

**Issue by Altanb1337** [Fyrax-exe/bucketware#9]
private static Random randomness = new Random();
        public static string RandomSTG(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[randomness.Next(s.Length)]).ToArray());
        }
        private async void button15_Click_3(object sender, EventArgs e)
        {
            //string[] lines = System.IO.File.ReadAllLines(@"C:\Users\xAnti\Desktop\llll.txt");

            //limitmarker1foreach (string line in lines)
            //{
            //messageHandler.packetSender.SendPacket(3, "action|validate_world\nname|" + line, realPeer);
            //int input = int.Parse(textBox8.Text);
            //textBox8.Text = (input + 1).ToString();
            //await Task.Delay(1);
            //}

            while (true)
            {
            string bruh = RandomSTG(4);
            messageHandler.packetSender.SendPacket(3, "action|validate_world\nname|" + bruh, realPeer);
             //messageHandler.packetSender.SendPacket(3, "action|join_request\nname|"+bruh+bruh+bruh+bruh+"\ninvitedWorld|0", realPeer);
                textBox8.Text = (int.Parse(textBox8.Text) + 1).ToString();
            await Task.Delay(1);
            }
        }

add it

**Comment by Fyrax-exe** [comment]
Sorry its useless

**Comment by Altanb1337** [comment]
> Sorry its useless

Finding 4 letter world not useless
